

service: diabetes_prediction


provider:
  name: aws
  runtime: python3.8

# you can overwrite defaults here
  stage: dev
  region: eu-central-1


package:

  exclude:
    - vscode/**
    - node_module/**

functions:
  hello:
    handler: handler.predict

    events:
      - http:
          path: predict-diabetes
          method: get
          request:
            parameters:
              queryString:
                Pregnancies: true
                Glucose: true
                BP: true
                SkinThickness: true
                Insulin: true
                BMI: true
                DiabetesPedigreeFunction: true
                Age: true

plugins:
  - serverless-python-requirements

  custom:
    pythonRequirement:
      dockerizePip: true
      slim: true